/*
 * Auto-generated tests for math_utils.c
 * Generated by MLTest
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <limits.h>

// Forward declaration
int safe_add(int a, int b);

void test_safe_add() {
    printf("Testing safe_add...\n");
    safe_add(0, 0);
    safe_add(1, 1);
    safe_add(5, 3);
    printf("  Basic tests completed\n");
}


// Forward declaration
int safe_multiply(int a, int b);

void test_safe_multiply() {
    printf("Testing safe_multiply...\n");
    safe_multiply(0, 0);
    safe_multiply(1, 1);
    safe_multiply(5, 3);
    printf("  Basic tests completed\n");
}


// Forward declaration
int safe_divide(int numerator, int denominator, int* result);

void test_safe_divide() {
    printf("Testing safe_divide...\n");
    safe_divide(0, 0, 0);
    printf("  Basic tests completed\n");
}


// Forward declaration
int gcd(int a, int b);

void test_gcd() {
    printf("Testing gcd...\n");
    gcd(0, 0);
    gcd(1, 1);
    gcd(5, 3);
    printf("  Basic tests completed\n");
}


// Forward declaration
long lcm(int a, int b);

void test_lcm() {
    printf("Testing lcm...\n");
    lcm(0, 0);
    lcm(1, 1);
    lcm(5, 3);
    printf("  Basic tests completed\n");
}


// Forward declaration
int is_prime(int n);

void test_is_prime() {
    printf("Testing is_prime...\n");
    is_prime(0);
    is_prime(1);
    is_prime(-1);
    printf("  Basic tests completed\n");
}


// Forward declaration
long factorial(int n);

void test_factorial() {
    printf("Testing factorial...\n");
    factorial(0);
    factorial(1);
    factorial(-1);
    printf("  Basic tests completed\n");
}


// Forward declaration
long fibonacci(int n);

void test_fibonacci() {
    printf("Testing fibonacci...\n");
    fibonacci(0);
    fibonacci(1);
    fibonacci(-1);
    printf("  Basic tests completed\n");
}


// Forward declaration
long power(int base, int exp);

void test_power() {
    printf("Testing power...\n");
    power(0, 0);
    power(1, 1);
    power(5, 3);
    printf("  Basic tests completed\n");
}


// Forward declaration
int isqrt(int n);

void test_isqrt() {
    printf("Testing isqrt...\n");
    isqrt(0);
    isqrt(1);
    isqrt(-1);
    printf("  Basic tests completed\n");
}


// Forward declaration
int abs_val(int x);

void test_abs_val() {
    printf("Testing abs_val...\n");
    abs_val(0);
    abs_val(1);
    abs_val(-1);
    printf("  Basic tests completed\n");
}


// Forward declaration
int clamp(int value, int min_val, int max_val);

void test_clamp() {
    printf("Testing clamp...\n");
    clamp(0, 0, 0);
    printf("  Basic tests completed\n");
}


// Forward declaration
int lerp(int a, int b, int t, int t_max);

void test_lerp() {
    printf("Testing lerp...\n");
    lerp(0, 0, 0, 0);
    printf("  Basic tests completed\n");
}


int main() {
    printf("Running 13 test suite(s)...\n\n");
    test_safe_add();
    test_safe_multiply();
    test_safe_divide();
    test_gcd();
    test_lcm();
    test_is_prime();
    test_factorial();
    test_fibonacci();
    test_power();
    test_isqrt();
    test_abs_val();
    test_clamp();
    test_lerp();
    printf("\nAll tests passed!\n");
    return 0;
}
